'use client';
import { useEffect, useState } from 'react';
import Link from 'next/link';
import {get,Metrics,metricFields,metricValue,money,num} from './lib';
type Listing = {id:number;property_id:number;address_line_1:string;city:string;zip_code:string;current_price:number|null;square_feet:number|null;ppsf:number|null;bedrooms:number|null;bathrooms:number|null;days_on_market:number|null;current_status:string;changed:string};
const filters = [['city','City'],['zip','ZIP code'],['min_price','Min price'],['max_price','Max price'],['min_sqft','Min sqft'],['max_sqft','Max sqft'],['beds','Min beds'],['baths','Min baths'],['min_year','Year from'],['max_year','Year to'],['type','Property type'],['min_lot','Min lot sqft'],['max_lot','Max lot sqft']];
export default function Dashboard(){
 const [query,setQuery]=useState('');const [page,setPage]=useState(0);const [sort,setSort]=useState('changed');const [direction,setDirection]=useState('desc');const [metrics,setMetrics]=useState<Metrics>();const [rows,setRows]=useState<Listing[]>([]);const [usage,setUsage]=useState<{requests:number;month:string;budget:number}>();const [error,setError]=useState('');const [loading,setLoading]=useState(true);
 useEffect(()=>{let alive=true;setLoading(true);setError('');Promise.all([get<Metrics>('analytics?'+query),get<Listing[]>(`listings?${query}&sort=${sort}&direction=${direction}&page=${page}`),get<{requests:number;month:string;budget:number}>('usage')]).then(([m,r,u])=>{if(alive){setMetrics(m);setRows(r);setUsage(u)}}).catch(e=>{if(alive)setError(e.message)}).finally(()=>{if(alive)setLoading(false)});return()=>{alive=false}},[query,sort,direction,page]);
 return <><div className="title"><div><p className="eyebrow">YOUR MARKET, OVER TIME</p><h1>Market dashboard</h1><p>Track inventory, price movement, and observed listing changes.</p></div><div className="usage">RentCast requests <strong>{usage?.requests ?? '—'} / {usage?.budget ?? 50}</strong><small>{usage?.month ?? 'Current month'} · UTC</small></div></div>
 <form onSubmit={e=>{e.preventDefault();const p=new URLSearchParams();new FormData(e.currentTarget).forEach((v,k)=>{if(String(v).trim())p.set(k,String(v).trim())});setQuery(p.toString());setPage(0)}}><h2>Explore your market</h2><div className="filters">{filters.map(([key,label])=><label key={key}>{label}<input name={key} type={['city','zip','type'].includes(key)?'text':'number'} min="0" step="any" placeholder={key==='type'?'Single Family':'Any'}/></label>)}</div><button>Apply filters</button><button type="reset" className="secondary" onClick={()=>{setQuery('');setPage(0)}}>Reset</button></form>
 {error?<p role="alert" className="error">{error}</p>:loading?<p role="status">Loading stored observations…</p>:<><section className="metrics">{metricFields.map(([key,label])=><article key={key}><span>{label}</span><strong>{metricValue(key,metrics?.[key])}</strong></article>)}</section><p className="muted">Price, DOM, and reduction metrics use active inventory. Relisting rate uses all matching listings and collected history.</p><section className="panel"><h2>Observed listings</h2><p>Includes active and inactive records. Select a heading to sort.</p><div className="table-wrap"><table><thead><tr>{[['address','Address'],['price','Price'],['sqft','Sqft'],['ppsf','$/sqft'],['beds','Beds'],['baths','Baths'],['dom','DOM'],['status','Status'],['changed','Last changed']].map(([key,label])=><th key={key}><button className="sort" onClick={()=>{setSort(key);setDirection(sort===key&&direction==='asc'?'desc':'asc');setPage(0)}}>{label}{sort===key?(direction==='asc'?' ↑':' ↓'):''}</button></th>)}</tr></thead><tbody>{rows.map(r=><tr key={r.id}><td><Link href={'/properties/'+r.property_id}>{r.address_line_1}</Link><small>{r.city} · {r.zip_code}</small></td><td>{money(r.current_price)}</td><td>{num(r.square_feet)}</td><td>{money(r.ppsf)}</td><td>{num(r.bedrooms)}</td><td>{num(r.bathrooms)}</td><td>{num(r.days_on_market)}</td><td><span className={'badge '+r.current_status.toLowerCase()}>{r.current_status}</span></td><td>{r.changed?new Date(r.changed).toLocaleDateString():'—'}</td></tr>)}</tbody></table></div>{rows.length===0&&<div className="empty"><h3>No listings yet</h3><p>Configure a search area and run ingestion, or adjust your filters. No sample data is shown.</p></div>}<div className="pagination"><button disabled={page===0} onClick={()=>setPage(page-1)}>Previous</button><span>Page {page+1}</span><button disabled={rows.length<100} onClick={()=>setPage(page+1)}>Next</button></div></section></>}
 </>;
}

